config/routes.rb
Rails.application.routes.draw do

  root 'home#landing'

   devise_for :users
  authenticated :user do
    root :to => 'home#index' , as: :authenticated_root
  end

  resources :users
  
  get "/privacy" => "home#privacy", as: :privacy
  get "/about" => "home#about", as: :about
  get "/contact" => "home#contact", as: :contact

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def new
	end

	def landing
	end

	def index
	end

	def privacy
	end

	def about
	end

	def contact
	end

end		

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/landing.html.erb
<% if user_signed_in? %>
<div class="list-group">
  <a href="#" class="list-group-item active">
  	<span class = "badge">14</span>
    School Example
  </a>
  <a href="#" class="list-group-item">Inactive reference example</a>
  <a href="#" class="list-group-item active">
  	<span class = "badge">5</span>
  	Org Example
  	</a>
  <a href="#" class="list-group-item">All Should Align to Left</a>
  <a href="#" class="list-group-item">All should have mini logos</a>
  <a href="#" class="list-group-item">Should be shorter</a>
  <a href="#" class="list-group-item">Could have different colors</a>  
</div>

<%else%>

<div class="jumbotron">
<div class = "text-center"> 
  <h1>Welcome to Kroo!</h1>
  <p>Create an account now</p>
<%= link_to "Sign Up", new_user_registration_path, {:class => "btn btn-primary btn-lg"} %>
<%= link_to "Sign Up with Facebook", new_user_registration_path, {:class => "btn btn-primary btn-lg"} %>
</div>
</div>
<!-- <div> 
<%= link_to "Sign Up", new_user_registration_path %>
<%= link_to "Sign In", new_user_session_path %>

</div> -->
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kroo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!--   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
 <%# Following install for devise gem/%> -->

</head>
<body>


<%= render "shared/navbar" %>
<div class ="container">
<%= yield %>
</div>
</body>
<%= render "shared/footer" %>
</html>

app/views/shared/_footer.erb
<footer>
	<div class ="container">
    <ul class="nav navbar-nav footer-nav">
      <li>
        <small>
          <%= link_to "Privacy Policy", privacy_path %>
        </small>
      </li>
      <li>
        <small>
          <%= link_to "About Us", about_path %>
        </small>
      </li>
      <li>
        <small>
          <%= link_to "Contact Us", contact_path %>
        </small>
      </li>
    </ul>
		<div class ="pull-right">
		<small> &copy; 2015 All Rights Reserved. </small>
		</div>
	</div>
</footer>

app/views/shared/_navbar.erb
<navbar>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">KROO</a>
    </div>

<% if user_signed_in? %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<!--        <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
-->

<!--        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> 

      </ul> -->

<form class="navbar-form navbar-left" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Find a Friend or an Event...">
  </div>
</form>

<ul class="nav navbar-nav navbar-right">
<%= link_to "Sign Out", destroy_user_session_path, {:class => "btn btn-default navbar-btn", :method => :delete} %>
</ul>


<!--    <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Preferences</a></li>
            <li><a href="#">Report a Problem</a></li>
            <li><a href="#"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul> 
        </li> -->
        <% else %>
              <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul> 
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</navbar>